### ISSUE TITLE
Deprecation warning on install

### ISSUE THREAD

**Issue by mpfdavis** [dainis/node-gcstats#21]
WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR

**Comment by dainis** [comment]
https://github.com/nodejs/node-gyp/issues/787
https://github.com/nodejs/node-gyp/pull/878
https://github.com/nodejs/node-gyp/blob/master/lib/process-release.js#L66-L75

Use correct env variable
