### ISSUE TITLE
License

### ISSUE THREAD

**Issue by paulrutter** [dainis/node-gcstats#23]
Hi,

I'm using your module in a project of ours, [node-oom-heapdump](https://github.com/blueconic/node-oom-heapdump/), which is distributed under MIT license. Do you have any issues with that, as gc-stats is licensed under Unlicense?

Thanks and keep up the good work.

**Comment by dainis** [comment]
No problem, [Unlicense](https://choosealicense.com/licenses/unlicense/) is as permissive  as it gets

**Comment by paulrutter** [comment]
Thanks, better be sure 👍
