### ISSUE TITLE
Fails to build on node 12.x

### ISSUE THREAD

**Issue by yvasiyarov** [dainis/node-gcstats#39]
Hello, 
I've made pull request with small changes in example.js and CI checks tells me that module fails to compile on Node 12.x

Obviously it can not be caused by example.js, so its looks like master is broken. It might be related with #36 issue.

**Comment by dainis** [comment]
That is issue with node itself 

https://github.com/nodejs/node/issues/27803
https://github.com/nodejs/node/pull/27814
