### ISSUE TITLE
node-gyp fails on windows7, node 0.12.2, npm 2.7.4, node-gyp 1.0.3

### ISSUE THREAD

**Issue by paul42** [dainis/node-gcstats#8]
It's probably me, but I thought I had node-gyp working for other projects, are there any steps for windows that I need to fulfill? or should I ask for help for this in the node-gyp repo?

npm-debug.log gist: https://gist.github.com/paul42/ec740031b28084d3c1d3
console output gist: https://gist.github.com/paul42/0772ca3f34266befe250

Thanks in advance,
Paul42

**Comment by dainis** [comment]
Sorry, but I don't have a PC with windows

My best guess is that it is node-gyp issue : https://github.com/TooTallNate/node-gyp/issues/506
